apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qd29xm3pj-nodejs
  janus-idp.io/tekton: qd29xm3pj-nodejs
  backstage.io/kubernetes-id: qd29xm3pj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qd29xm3pj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
