apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qd29xm3pj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qd29xm3pj-nodejs 
  name: qd29xm3pj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qd29xm3pj-nodejs 
